/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 colonization_ship.glb 
Author: Renham - Camilo Rojas (https://sketchfab.com/renham)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/colonization-ship-uei-opportunity-9fd1f31d74c941538d11d1e98d8866bf
Title: Colonization Ship - UEI OPPORTUNITY
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ColonizationShip(props) {
  const { nodes, materials } = useGLTF('/models/colonization_ship.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.005, -0.002, -0.395]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['19_ring_modules']} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials['20_weaponry_autocannon']} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials['21_weaponry_cannonhull']} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.energy_core} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.fustion_core} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.reactor_armor} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.bracers} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.cooler_tanks} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.pipes} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.small_pipes} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.module_for_reactor} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.cargo_bay} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.collectors} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.plugs} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.module_for_cargo} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials['17_cargo_container']} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.habitat_ring} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.inside_habitat} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.sub_thruster_ring} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.ring_structure} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.ftl_main_module} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.Main_thruster_module} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.thrusters_main} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.thrusters} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials['20_weaponry_autocannon']} />
          <mesh geometry={nodes.defaultMaterial_25.geometry} material={materials['21_weaponry_cannonhull']} />
          <mesh geometry={nodes.defaultMaterial_26.geometry} material={materials['19_ring_modules']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/colonization_ship.glb')
