/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 milky_way_sky.glb --transform 
Files: milky_way_sky.glb [7.61MB] > /Users/Ian/Code/Web/my-blog/public/models/milky_way_sky-transformed.glb [136.06KB] (98%)
Author: Aliaksandr.melas (https://sketchfab.com/alexandr.melas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/milky-way-skybox-hdri-panorama-b57711d6a450410ca612c4a36f08ce21
Title: Milky Way Skybox HDRI panorama
*/
import { Suspense } from "react";
import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";
import { useLoading } from "@/hooks/LoadingContext";

export default function MilkySky({ modelId }) {
  const sky = useGLTF("/models/milky_way_sky.glb");
  const skyRef = useRef();
  const { scene: threeScene } = useThree();
  const { registerModel, unregisterModel, isLoading, setLoading } =
    useLoading();

  useEffect(() => {
    registerModel(modelId);
    return () => unregisterModel(modelId);
  }, [modelId, registerModel, unregisterModel]);

  useFrame((_, delta) => {
    if (
      isLoading &&
      threeScene &&
      sky.scene &&
      threeScene.getObjectById(sky.scene.id)
    ) {
      console.log("useframe unregisterModel");
      unregisterModel(modelId); // 当模型被实际渲染到场景中时，设置加载为false
    }
    skyRef.current.rotation.y += 0.0125 * delta; // Adjust the rotation speed as needed
  });

  return (
    <Suspense
      fallback={<div>Loading model...</div>}
      onResolve={() => setLoading(false)}
    >
      <a.group dispose={null} scale={[100, 100, 100]} position={[0, 0, -1]}>
        <mesh ref={skyRef}>
          <primitive object={sky.scene} />
        </mesh>
      </a.group>
    </Suspense>
  );
}

useGLTF.preload("/models/milky_way_sky.glb");
